### ISSUE TITLE
what commit hash for jsapi.sh and friends?

### ISSUE THREAD

**Issue by shapr** [yetamrra/spc-compiler#1]
I'm trying to build this, but I'm having trouble finding which commit hash included jsapi.sh and related pieces.
If you happen to remember, would make my life easier!

Thanks for releasing this source!

**Comment by yetamrra** [comment]
Hey, sorry about the slow reply.  I believe I used sphinx4-beta5 from https://sourceforge.net/projects/cmusphinx/files/sphinx4/1.0%20beta5/ .  I haven't tried to compile this in the last couple of years, but if you're interested in using it I can try to update things for current versions.

**Comment by shapr** [comment]
I am very interested in getting this to compile again, but it's beyond my outdated Java skills.
I'd like to use it, and I'm interested in building something similar for myself.

**Comment by yetamrra** [comment]
I'll try to get this going again with more recent versions next week.  Just to set expectations, though: This is a research language used to test some hypotheses in my thesis. You're more than welcome to use it or extend it if it suits your needs, but don't expect to get any real programming done with it in the current state.

**Comment by shapr** [comment]
I understand, I want to use this to get the feel of it. 
I want to build my own spoken programming language, and this is the only spoken programming language I found when searching the literature.

**Comment by yetamrra** [comment]
OK, I've updated the README for both projects with extra details and links to the exact versions I used.  I was able to build the compiler and plugin on Eclipse 2019-03 and dictate a small program.

Please send me a pointer if you end up doing anything interesting with this.  I'd love to see more progress in this area!
